// ── Predictive Alert Model ──
// Persists all alerts generated by the Predictive Intelligence Engine.
// Supports acknowledgement, escalation, and full history search.

import mongoose from 'mongoose';

const alertSchema = new mongoose.Schema({
    shipmentId: { type: String, required: true, index: true },
    type: {
        type: String,
        enum: ['RISK_HIGH', 'REROUTE_SUGGESTED', 'DELAY_CRITICAL', 'WEATHER_WARNING', 'NETWORK_CONGESTION'],
        required: true,
    },
    title: { type: String, required: true },
    message: { type: String, required: true },
    actionRequired: { type: Boolean, default: false },
    suggestedAction: { type: String, default: '' },
    actionLink: { type: String, default: '' },
    read: { type: Boolean, default: false },
    acknowledged: { type: Boolean, default: false },
    escalated: { type: Boolean, default: false },
    userId: { type: String, index: true },       // target user (owner/customer)
    riskScore: { type: Number },
    riskLevel: { type: String },
}, {
    timestamps: true,
});

// Compound indexes for efficient queries
alertSchema.index({ userId: 1, read: 1, createdAt: -1 });
alertSchema.index({ type: 1, createdAt: -1 });
alertSchema.index({ shipmentId: 1, type: 1, createdAt: -1 });

export const AlertModel = mongoose.model('Alert', alertSchema);
